import os, sys, re, csv, sqlite3, string
from datetime import datetime, timedelta
from time import strptime, strftime
from itertools import chain

if len(sys.argv) > 3:
	sys.stderr.write("Use l2tf.py <input filename> <header/no header option)\nExample: l2tf.py App.evtx.out\"\n         \"l2tf.py App.evtx.out -h  \n\n")
	sys.exit(1)
if len(sys.argv) == 2:
	printheader = "yes"
else:
	if len(sys.argv) == 3:
		if sys.argv[2] == "-h":
			printheader = "no"
		else:
			sys.stderr.write("Use l2tf.py <input filename> <header/no header option)\nExample: l2tf.py App.evtx.out\n         l2tf.py App.evtx.out -h  \n\n")
			sys.exit(1)
	else:
		if len(sys.argv) != 3:
			sys.stderr.write("Use l2tf.py <input filename> <header/no header option)\nExample: l2tf.py App.evtx.out\n         l2tf.py App.evtx.out -h  \n\n")
			sys.exit(1)

print("Converting file: ", sys.argv[1])
print("Loading Windows Event ID Database")
# Create eventid lookup database
edb = sqlite3.connect(":memory:")
edb.execute('''CREATE TABLE Events (eventid, definition)''')
edb.execute("INSERT INTO Events VALUES ('512','Windows NT is starting up')")
edb.execute("INSERT INTO Events VALUES ('513','Windows is shutting down')")
edb.execute("INSERT INTO Events VALUES ('514','An authentication package has been loaded by the Local Security Authority')")
edb.execute("INSERT INTO Events VALUES ('515','A trusted logon process has registered with the Local Security Authority')")
edb.execute("INSERT INTO Events VALUES ('516','Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits')")
edb.execute("INSERT INTO Events VALUES ('517','The audit log was cleared')")
edb.execute("INSERT INTO Events VALUES ('518','A notification package has been loaded by the Security Account Manager')")
edb.execute("INSERT INTO Events VALUES ('519','A process is using an invalid local procedure call (LPC) port')")
edb.execute("INSERT INTO Events VALUES ('520','The system time was changed')")
edb.execute("INSERT INTO Events VALUES ('528','Successful Logon')")
edb.execute("INSERT INTO Events VALUES ('529','Logon Failure - Unknown user name or bad password')")
edb.execute("INSERT INTO Events VALUES ('530','Logon Failure - Account logon time restriction violation')")
edb.execute("INSERT INTO Events VALUES ('531','Logon Failure - Account currently disabled')")
edb.execute("INSERT INTO Events VALUES ('532','Logon Failure - The specified user account has expired')")
edb.execute("INSERT INTO Events VALUES ('533','Logon Failure - User not allowed to logon at this computer')")
edb.execute("INSERT INTO Events VALUES ('534','Logon Failure - The user has not been granted the requested logon type at this machine')")
edb.execute("INSERT INTO Events VALUES ('535','Logon Failure - The specified account password has expired')")
edb.execute("INSERT INTO Events VALUES ('536','Logon Failure - The NetLogon component is not active')")
edb.execute("INSERT INTO Events VALUES ('537','Logon failure - The logon attempt failed for other reasons.')")
edb.execute("INSERT INTO Events VALUES ('538','User Logoff')")
edb.execute("INSERT INTO Events VALUES ('539','Logon Failure - Account locked out')")
edb.execute("INSERT INTO Events VALUES ('540','Successful Network Logon')")
edb.execute("INSERT INTO Events VALUES ('551','User initiated logoff')")
edb.execute("INSERT INTO Events VALUES ('552','Logon attempt using explicit credentials')")
edb.execute("INSERT INTO Events VALUES ('560','Object Open')")
edb.execute("INSERT INTO Events VALUES ('561','Handle Allocated')")
edb.execute("INSERT INTO Events VALUES ('562','Handle Closed')")
edb.execute("INSERT INTO Events VALUES ('563','Object Open for Delete')")
edb.execute("INSERT INTO Events VALUES ('564','Object Deleted')")
edb.execute("INSERT INTO Events VALUES ('565','Object Open (Active Directory)')")
edb.execute("INSERT INTO Events VALUES ('566','Object Operation (W3 Active Directory)')")
edb.execute("INSERT INTO Events VALUES ('567','Object Access Attempt')")
edb.execute("INSERT INTO Events VALUES ('576','Special privileges assigned to new logon')")
edb.execute("INSERT INTO Events VALUES ('577','Privileged Service Called')")
edb.execute("INSERT INTO Events VALUES ('578','Privileged object operation')")
edb.execute("INSERT INTO Events VALUES ('592','A new process has been created')")
edb.execute("INSERT INTO Events VALUES ('593','A process has exited')")
edb.execute("INSERT INTO Events VALUES ('594','A handle to an object has been duplicated')")
edb.execute("INSERT INTO Events VALUES ('595','Indirect access to an object has been obtained')")
edb.execute("INSERT INTO Events VALUES ('600','A process was assigned a primary token')")
edb.execute("INSERT INTO Events VALUES ('601','Attempt to install service')")
edb.execute("INSERT INTO Events VALUES ('602','Scheduled Task created')")
edb.execute("INSERT INTO Events VALUES ('608','User Right Assigned')")
edb.execute("INSERT INTO Events VALUES ('609','User Right Removed')")
edb.execute("INSERT INTO Events VALUES ('610','New Trusted Domain')")
edb.execute("INSERT INTO Events VALUES ('611','Removing Trusted Domain')")
edb.execute("INSERT INTO Events VALUES ('612','Audit Policy Change')")
edb.execute("INSERT INTO Events VALUES ('613','IPSec policy agent started')")
edb.execute("INSERT INTO Events VALUES ('614','IPSec policy agent disabled')")
edb.execute("INSERT INTO Events VALUES ('615','IPSEC PolicyAgent Service')")
edb.execute("INSERT INTO Events VALUES ('616','IPSec policy agent encountered a potentially serious failure.')")
edb.execute("INSERT INTO Events VALUES ('617','Kerberos Policy Changed')")
edb.execute("INSERT INTO Events VALUES ('618','Encrypted Data Recovery Policy Changed')")
edb.execute("INSERT INTO Events VALUES ('619','Quality of Service Policy Changed')")
edb.execute("INSERT INTO Events VALUES ('620','Trusted Domain Information Modified')")
edb.execute("INSERT INTO Events VALUES ('621','System Security Access Granted')")
edb.execute("INSERT INTO Events VALUES ('622','System Security Access Removed')")
edb.execute("INSERT INTO Events VALUES ('623','Per User Audit Policy was refreshed')")
edb.execute("INSERT INTO Events VALUES ('624','User Account Created')")
edb.execute("INSERT INTO Events VALUES ('625','User Account Type Changed')")
edb.execute("INSERT INTO Events VALUES ('626','User Account Enabled')")
edb.execute("INSERT INTO Events VALUES ('627','Change Password Attempt')")
edb.execute("INSERT INTO Events VALUES ('628','User Account password set')")
edb.execute("INSERT INTO Events VALUES ('629','User Account Disabled')")
edb.execute("INSERT INTO Events VALUES ('630','User Account Deleted')")
edb.execute("INSERT INTO Events VALUES ('631','Security Enabled Global Group Created')")
edb.execute("INSERT INTO Events VALUES ('632','Security Enabled Global Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('633','Security Enabled Global Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('634','Security Enabled Global Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('635','Security Enabled Local Group Created')")
edb.execute("INSERT INTO Events VALUES ('636','Security Enabled Local Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('637','Security Enabled Local Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('638','Security Enabled Local Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('639','Security Enabled Local Group Changed')")
edb.execute("INSERT INTO Events VALUES ('640','General Account Database Change')")
edb.execute("INSERT INTO Events VALUES ('641','Security Enabled Global Group Changed')")
edb.execute("INSERT INTO Events VALUES ('642','User Account Changed')")
edb.execute("INSERT INTO Events VALUES ('643','Domain Policy Changed')")
edb.execute("INSERT INTO Events VALUES ('644','User Account Locked Out')")
edb.execute("INSERT INTO Events VALUES ('645','Computer Account Created')")
edb.execute("INSERT INTO Events VALUES ('646','Computer Account Changed')")
edb.execute("INSERT INTO Events VALUES ('647','Computer Account Deleted')")
edb.execute("INSERT INTO Events VALUES ('648','Security Disabled Local Group Created')")
edb.execute("INSERT INTO Events VALUES ('649','Security Disabled Local Group Changed')")
edb.execute("INSERT INTO Events VALUES ('650','Security Disabled Local Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('651','Security Disabled Local Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('652','Security Disabled Local Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('653','Security Disabled Global Group Created')")
edb.execute("INSERT INTO Events VALUES ('654','Security Disabled Global Group Changed')")
edb.execute("INSERT INTO Events VALUES ('655','Security Disabled Global Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('656','Security Disabled Global Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('657','Security Disabled Global Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('658','Security Enabled Universal Group Created')")
edb.execute("INSERT INTO Events VALUES ('659','Security Enabled Universal Group Changed')")
edb.execute("INSERT INTO Events VALUES ('660','Security Enabled Universal Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('661','Security Enabled Universal Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('662','Security Enabled Universal Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('663','Security Disabled Universal Group Created')")
edb.execute("INSERT INTO Events VALUES ('664','Security Disabled Universal Group Changed')")
edb.execute("INSERT INTO Events VALUES ('665','Security Disabled Universal Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('666','Security Disabled Universal Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('667','Security Disabled Universal Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('668','Group Type Changed')")
edb.execute("INSERT INTO Events VALUES ('669','Add SID History')")
edb.execute("INSERT INTO Events VALUES ('670','Add SID History')")
edb.execute("INSERT INTO Events VALUES ('671','User Account Unlocked')")
edb.execute("INSERT INTO Events VALUES ('672','Authentication Ticket Granted')")
edb.execute("INSERT INTO Events VALUES ('673','Service Ticket Granted')")
edb.execute("INSERT INTO Events VALUES ('674','Ticket Granted Renewed')")
edb.execute("INSERT INTO Events VALUES ('675','Pre-authentication failed')")
edb.execute("INSERT INTO Events VALUES ('676','Authentication Ticket Request Failed')")
edb.execute("INSERT INTO Events VALUES ('677','Service Ticket Request Failed')")
edb.execute("INSERT INTO Events VALUES ('678','Account Mapped for Logon by')")
edb.execute("INSERT INTO Events VALUES ('679','The name: %2 could not be mapped for logon by: %1')")
edb.execute("INSERT INTO Events VALUES ('680','Account Used for Logon by')")
edb.execute("INSERT INTO Events VALUES ('681','The logon to account: %2 by: %1 from workstation: %3 failed.')")
edb.execute("INSERT INTO Events VALUES ('682','Session reconnected to winstation')")
edb.execute("INSERT INTO Events VALUES ('683','Session disconnected from winstation')")
edb.execute("INSERT INTO Events VALUES ('684','Set ACLs of members in administrators groups')")
edb.execute("INSERT INTO Events VALUES ('685','Account Name Changed')")
edb.execute("INSERT INTO Events VALUES ('686','Password of the following user accessed')")
edb.execute("INSERT INTO Events VALUES ('687','Basic Application Group Created')")
edb.execute("INSERT INTO Events VALUES ('688','Basic Application Group Changed')")
edb.execute("INSERT INTO Events VALUES ('689','Basic Application Group Member Added')")
edb.execute("INSERT INTO Events VALUES ('690','Basic Application Group Member Removed')")
edb.execute("INSERT INTO Events VALUES ('691','Basic Application Group Non-Member Added')")
edb.execute("INSERT INTO Events VALUES ('692','Basic Application Group Non-Member Removed')")
edb.execute("INSERT INTO Events VALUES ('693','Basic Application Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('694','LDAP Query Group Created')")
edb.execute("INSERT INTO Events VALUES ('695','LDAP Query Group Changed')")
edb.execute("INSERT INTO Events VALUES ('696','LDAP Query Group Deleted')")
edb.execute("INSERT INTO Events VALUES ('697','Password Policy Checking API is called')")
edb.execute("INSERT INTO Events VALUES ('806','Per User Audit Policy was refreshed')")
edb.execute("INSERT INTO Events VALUES ('807','Per user auditing policy set for user')")
edb.execute("INSERT INTO Events VALUES ('808','A security event source has attempted to register')")
edb.execute("INSERT INTO Events VALUES ('809','A security event source has attempted to unregister')")
edb.execute("INSERT INTO Events VALUES ('848','The following policy was active when the Windows Firewall started')")
edb.execute("INSERT INTO Events VALUES ('849','An application was listed as an exception when the Windows Firewall started')")
edb.execute("INSERT INTO Events VALUES ('850','A port was listed as an exception when the Windows Firewall started')")
edb.execute("INSERT INTO Events VALUES ('852','A change has been made to the Windows Firewall port exception list')")
edb.execute("INSERT INTO Events VALUES ('861','The Windows Firewall has detected an application listening for incoming traffic')")
edb.execute("INSERT INTO Events VALUES ('1100','The event logging service has shut down')")
edb.execute("INSERT INTO Events VALUES ('1101','Audit events have been dropped by the transport.')")
edb.execute("INSERT INTO Events VALUES ('1102','The audit log was cleared')")
edb.execute("INSERT INTO Events VALUES ('1104','The security Log is now full')")
edb.execute("INSERT INTO Events VALUES ('1105','Event log automatic backup')")
edb.execute("INSERT INTO Events VALUES ('1108','The event logging service encountered an error')")
edb.execute("INSERT INTO Events VALUES ('4608','Windows is starting up')")
edb.execute("INSERT INTO Events VALUES ('4609','Windows is shutting down')")
edb.execute("INSERT INTO Events VALUES ('4610','An authentication package has been loaded by the Local Security Authority')")
edb.execute("INSERT INTO Events VALUES ('4611','A trusted logon process has been registered with the Local Security Authority')")
edb.execute("INSERT INTO Events VALUES ('4612','Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits.')")
edb.execute("INSERT INTO Events VALUES ('4614','A notification package has been loaded by the Security Account Manager.')")
edb.execute("INSERT INTO Events VALUES ('4615','Invalid use of LPC port')")
edb.execute("INSERT INTO Events VALUES ('4616','The system time was changed.')")
edb.execute("INSERT INTO Events VALUES ('4618','A monitored security event pattern has occurred')")
edb.execute("INSERT INTO Events VALUES ('4621','Administrator recovered system from CrashOnAuditFail')")
edb.execute("INSERT INTO Events VALUES ('4622','A security package has been loaded by the Local Security Authority.')")
edb.execute("INSERT INTO Events VALUES ('4624','An account was successfully logged on')")
edb.execute("INSERT INTO Events VALUES ('4625','An account failed to log on')")
edb.execute("INSERT INTO Events VALUES ('4634','An account was logged off')")
edb.execute("INSERT INTO Events VALUES ('4646','IKE DoS-prevention mode started.')")
edb.execute("INSERT INTO Events VALUES ('4647','User initiated logoff')")
edb.execute("INSERT INTO Events VALUES ('4648','A logon was attempted using explicit credentials')")
edb.execute("INSERT INTO Events VALUES ('4649','A replay attack was detected')")
edb.execute("INSERT INTO Events VALUES ('4650','An IPsec Main Mode security association was established')")
edb.execute("INSERT INTO Events VALUES ('4651','An IPsec Main Mode security association was established')")
edb.execute("INSERT INTO Events VALUES ('4652','An IPsec Main Mode negotiation failed')")
edb.execute("INSERT INTO Events VALUES ('4653','An IPsec Main Mode negotiation failed')")
edb.execute("INSERT INTO Events VALUES ('4654','An IPsec Quick Mode negotiation failed')")
edb.execute("INSERT INTO Events VALUES ('4655','An IPsec Main Mode security association ended')")
edb.execute("INSERT INTO Events VALUES ('4656','A handle to an object was requested')")
edb.execute("INSERT INTO Events VALUES ('4657','A registry value was modified')")
edb.execute("INSERT INTO Events VALUES ('4658','The handle to an object was closed')")
edb.execute("INSERT INTO Events VALUES ('4659','A handle to an object was requested with intent to delete')")
edb.execute("INSERT INTO Events VALUES ('4660','An object was deleted')")
edb.execute("INSERT INTO Events VALUES ('4661','A handle to an object was requested')")
edb.execute("INSERT INTO Events VALUES ('4662','An operation was performed on an object')")
edb.execute("INSERT INTO Events VALUES ('4663','An attempt was made to access an object')")
edb.execute("INSERT INTO Events VALUES ('4664','An attempt was made to create a hard link')")
edb.execute("INSERT INTO Events VALUES ('4665','An attempt was made to create an application client context.')")
edb.execute("INSERT INTO Events VALUES ('4666','An application attempted an operation')")
edb.execute("INSERT INTO Events VALUES ('4667','An application client context was deleted')")
edb.execute("INSERT INTO Events VALUES ('4668','An application was initialized')")
edb.execute("INSERT INTO Events VALUES ('4670','Permissions on an object were changed')")
edb.execute("INSERT INTO Events VALUES ('4671','An application attempted to access a blocked ordinal through the TBS')")
edb.execute("INSERT INTO Events VALUES ('4672','Special privileges assigned to new logon')")
edb.execute("INSERT INTO Events VALUES ('4673','A privileged service was called')")
edb.execute("INSERT INTO Events VALUES ('4674','An operation was attempted on a privileged object')")
edb.execute("INSERT INTO Events VALUES ('4675','SIDs were filtered')")
edb.execute("INSERT INTO Events VALUES ('4688','A new process has been created')")
edb.execute("INSERT INTO Events VALUES ('4689','A process has exited')")
edb.execute("INSERT INTO Events VALUES ('4690','An attempt was made to duplicate a handle to an object')")
edb.execute("INSERT INTO Events VALUES ('4691','Indirect access to an object was requested')")
edb.execute("INSERT INTO Events VALUES ('4692','Backup of data protection master key was attempted')")
edb.execute("INSERT INTO Events VALUES ('4693','Recovery of data protection master key was attempted')")
edb.execute("INSERT INTO Events VALUES ('4694','Protection of auditable protected data was attempted')")
edb.execute("INSERT INTO Events VALUES ('4695','Unprotection of auditable protected data was attempted')")
edb.execute("INSERT INTO Events VALUES ('4696','A primary token was assigned to process')")
edb.execute("INSERT INTO Events VALUES ('4697','A service was installed in the system')")
edb.execute("INSERT INTO Events VALUES ('4698','A scheduled task was created')")
edb.execute("INSERT INTO Events VALUES ('4699','A scheduled task was deleted')")
edb.execute("INSERT INTO Events VALUES ('4700','A scheduled task was enabled')")
edb.execute("INSERT INTO Events VALUES ('4701','A scheduled task was disabled')")
edb.execute("INSERT INTO Events VALUES ('4702','A scheduled task was updated')")
edb.execute("INSERT INTO Events VALUES ('4704','A user right was assigned')")
edb.execute("INSERT INTO Events VALUES ('4705','A user right was removed')")
edb.execute("INSERT INTO Events VALUES ('4706','A new trust was created to a domain')")
edb.execute("INSERT INTO Events VALUES ('4707','A trust to a domain was removed')")
edb.execute("INSERT INTO Events VALUES ('4709','IPsec Services was started')")
edb.execute("INSERT INTO Events VALUES ('4710','IPsec Services was disabled')")
edb.execute("INSERT INTO Events VALUES ('4711','PAStore Engine (1%)')")
edb.execute("INSERT INTO Events VALUES ('4712','IPsec Services encountered a potentially serious failure')")
edb.execute("INSERT INTO Events VALUES ('4713','Kerberos policy was changed')")
edb.execute("INSERT INTO Events VALUES ('4714','Encrypted data recovery policy was changed')")
edb.execute("INSERT INTO Events VALUES ('4715','The audit policy (SACL) on an object was changed')")
edb.execute("INSERT INTO Events VALUES ('4716','Trusted domain information was modified')")
edb.execute("INSERT INTO Events VALUES ('4717','System security access was granted to an account')")
edb.execute("INSERT INTO Events VALUES ('4718','System security access was removed from an account')")
edb.execute("INSERT INTO Events VALUES ('4719','System audit policy was changed')")
edb.execute("INSERT INTO Events VALUES ('4720','A user account was created')")
edb.execute("INSERT INTO Events VALUES ('4722','A user account was enabled')")
edb.execute("INSERT INTO Events VALUES ('4723','An attempt was made to change an account password')")
edb.execute("INSERT INTO Events VALUES ('4724','An attempt was made to reset an accounts password')")
edb.execute("INSERT INTO Events VALUES ('4725','A user account was disabled')")
edb.execute("INSERT INTO Events VALUES ('4726','A user account was deleted')")
edb.execute("INSERT INTO Events VALUES ('4727','A security-enabled global group was created')")
edb.execute("INSERT INTO Events VALUES ('4728','A member was added to a security-enabled global group')")
edb.execute("INSERT INTO Events VALUES ('4729','A member was removed from a security-enabled global group')")
edb.execute("INSERT INTO Events VALUES ('4730','A security-enabled global group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4731','A security-enabled local group was created')")
edb.execute("INSERT INTO Events VALUES ('4732','A member was added to a security-enabled local group')")
edb.execute("INSERT INTO Events VALUES ('4733','A member was removed from a security-enabled local group')")
edb.execute("INSERT INTO Events VALUES ('4734','A security-enabled local group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4735','A security-enabled local group was changed')")
edb.execute("INSERT INTO Events VALUES ('4737','A security-enabled global group was changed')")
edb.execute("INSERT INTO Events VALUES ('4738','A user account was changed')")
edb.execute("INSERT INTO Events VALUES ('4739','Domain Policy was changed')")
edb.execute("INSERT INTO Events VALUES ('4740','A user account was locked out')")
edb.execute("INSERT INTO Events VALUES ('4741','A computer account was created')")
edb.execute("INSERT INTO Events VALUES ('4742','A computer account was changed')")
edb.execute("INSERT INTO Events VALUES ('4743','A computer account was deleted')")
edb.execute("INSERT INTO Events VALUES ('4744','A security-disabled local group was created')")
edb.execute("INSERT INTO Events VALUES ('4745','A security-disabled local group was changed')")
edb.execute("INSERT INTO Events VALUES ('4746','A member was added to a security-disabled local group')")
edb.execute("INSERT INTO Events VALUES ('4747','A member was removed from a security-disabled local group')")
edb.execute("INSERT INTO Events VALUES ('4748','A security-disabled local group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4749','A security-disabled global group was created')")
edb.execute("INSERT INTO Events VALUES ('4750','A security-disabled global group was changed')")
edb.execute("INSERT INTO Events VALUES ('4751','A member was added to a security-disabled global group')")
edb.execute("INSERT INTO Events VALUES ('4752','A member was removed from a security-disabled global group')")
edb.execute("INSERT INTO Events VALUES ('4753','A security-disabled global group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4754','A security-enabled universal group was created')")
edb.execute("INSERT INTO Events VALUES ('4755','A security-enabled universal group was changed')")
edb.execute("INSERT INTO Events VALUES ('4756','A member was added to a security-enabled universal group')")
edb.execute("INSERT INTO Events VALUES ('4757','A member was removed from a security-enabled universal group')")
edb.execute("INSERT INTO Events VALUES ('4758','A security-enabled universal group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4759','A security-disabled universal group was created')")
edb.execute("INSERT INTO Events VALUES ('4760','A security-disabled universal group was changed')")
edb.execute("INSERT INTO Events VALUES ('4761','A member was added to a security-disabled universal group')")
edb.execute("INSERT INTO Events VALUES ('4762','A member was removed from a security-disabled universal group')")
edb.execute("INSERT INTO Events VALUES ('4763','A security-disabled universal group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4764','A groups type was changed')")
edb.execute("INSERT INTO Events VALUES ('4765','SID History was added to an account')")
edb.execute("INSERT INTO Events VALUES ('4766','An attempt to add SID History to an account failed')")
edb.execute("INSERT INTO Events VALUES ('4767','A user account was unlocked')")
edb.execute("INSERT INTO Events VALUES ('4768','A Kerberos authentication ticket (TGT) was requested')")
edb.execute("INSERT INTO Events VALUES ('4769','A Kerberos service ticket was requested')")
edb.execute("INSERT INTO Events VALUES ('4770','A Kerberos service ticket was renewed')")
edb.execute("INSERT INTO Events VALUES ('4771','Kerberos pre-authentication failed')")
edb.execute("INSERT INTO Events VALUES ('4772','A Kerberos authentication ticket request failed')")
edb.execute("INSERT INTO Events VALUES ('4773','A Kerberos service ticket request failed')")
edb.execute("INSERT INTO Events VALUES ('4774','An account was mapped for logon')")
edb.execute("INSERT INTO Events VALUES ('4775','An account could not be mapped for logon')")
edb.execute("INSERT INTO Events VALUES ('4776','The domain controller attempted to validate the credentials for an account')")
edb.execute("INSERT INTO Events VALUES ('4777','The domain controller failed to validate the credentials for an account')")
edb.execute("INSERT INTO Events VALUES ('4778','A session was reconnected to a Window Station')")
edb.execute("INSERT INTO Events VALUES ('4779','A session was disconnected from a Window Station')")
edb.execute("INSERT INTO Events VALUES ('4780','The ACL was set on accounts which are members of administrators groups')")
edb.execute("INSERT INTO Events VALUES ('4781','The name of an account was changed')")
edb.execute("INSERT INTO Events VALUES ('4782','The password hash an account was accessed')")
edb.execute("INSERT INTO Events VALUES ('4783','A basic application group was created')")
edb.execute("INSERT INTO Events VALUES ('4784','A basic application group was changed')")
edb.execute("INSERT INTO Events VALUES ('4785','A member was added to a basic application group')")
edb.execute("INSERT INTO Events VALUES ('4786','A member was removed from a basic application group')")
edb.execute("INSERT INTO Events VALUES ('4787','A non-member was added to a basic application group')")
edb.execute("INSERT INTO Events VALUES ('4788','A non-member was removed from a basic application group..')")
edb.execute("INSERT INTO Events VALUES ('4789','A basic application group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4790','An LDAP query group was created')")
edb.execute("INSERT INTO Events VALUES ('4791','A basic application group was changed')")
edb.execute("INSERT INTO Events VALUES ('4792','An LDAP query group was deleted')")
edb.execute("INSERT INTO Events VALUES ('4793','The Password Policy Checking API was called')")
edb.execute("INSERT INTO Events VALUES ('4794','An attempt was made to set the Directory Services Restore Mode administrator password')")
edb.execute("INSERT INTO Events VALUES ('4800','The workstation was locked')")
edb.execute("INSERT INTO Events VALUES ('4801','The workstation was unlocked')")
edb.execute("INSERT INTO Events VALUES ('4802','The screen saver was invoked')")
edb.execute("INSERT INTO Events VALUES ('4803','The screen saver was dismissed')")
edb.execute("INSERT INTO Events VALUES ('4816','RPC detected an integrity violation while decrypting an incoming message')")
edb.execute("INSERT INTO Events VALUES ('4817','Auditing settings on object were changed.')")
edb.execute("INSERT INTO Events VALUES ('4864','A namespace collision was detected')")
edb.execute("INSERT INTO Events VALUES ('4865','A trusted forest information entry was added')")
edb.execute("INSERT INTO Events VALUES ('4866','A trusted forest information entry was removed')")
edb.execute("INSERT INTO Events VALUES ('4867','A trusted forest information entry was modified')")
edb.execute("INSERT INTO Events VALUES ('4868','The certificate manager denied a pending certificate request')")
edb.execute("INSERT INTO Events VALUES ('4869','Certificate Services received a resubmitted certificate request')")
edb.execute("INSERT INTO Events VALUES ('4870','Certificate Services revoked a certificate')")
edb.execute("INSERT INTO Events VALUES ('4871','Certificate Services received a request to publish the certificate revocation list (CRL)')")
edb.execute("INSERT INTO Events VALUES ('4872','Certificate Services published the certificate revocation list (CRL)')")
edb.execute("INSERT INTO Events VALUES ('4873','A certificate request extension changed')")
edb.execute("INSERT INTO Events VALUES ('4874','One or more certificate request attributes changed.')")
edb.execute("INSERT INTO Events VALUES ('4875','Certificate Services received a request to shut down')")
edb.execute("INSERT INTO Events VALUES ('4876','Certificate Services backup started')")
edb.execute("INSERT INTO Events VALUES ('4877','Certificate Services backup completed')")
edb.execute("INSERT INTO Events VALUES ('4878','Certificate Services restore started')")
edb.execute("INSERT INTO Events VALUES ('4879','Certificate Services restore completed')")
edb.execute("INSERT INTO Events VALUES ('4880','Certificate Services started')")
edb.execute("INSERT INTO Events VALUES ('4881','Certificate Services stopped')")
edb.execute("INSERT INTO Events VALUES ('4882','The security permissions for Certificate Services changed')")
edb.execute("INSERT INTO Events VALUES ('4883','Certificate Services retrieved an archived key')")
edb.execute("INSERT INTO Events VALUES ('4884','Certificate Services imported a certificate into its database')")
edb.execute("INSERT INTO Events VALUES ('4885','The audit filter for Certificate Services changed')")
edb.execute("INSERT INTO Events VALUES ('4886','Certificate Services received a certificate request')")
edb.execute("INSERT INTO Events VALUES ('4887','Certificate Services approved a certificate request and issued a certificate')")
edb.execute("INSERT INTO Events VALUES ('4888','Certificate Services denied a certificate request')")
edb.execute("INSERT INTO Events VALUES ('4889','Certificate Services set the status of a certificate request to pending')")
edb.execute("INSERT INTO Events VALUES ('4890','The certificate manager settings for Certificate Services changed.')")
edb.execute("INSERT INTO Events VALUES ('4891','A configuration entry changed in Certificate Services')")
edb.execute("INSERT INTO Events VALUES ('4892','A property of Certificate Services changed')")
edb.execute("INSERT INTO Events VALUES ('4893','Certificate Services archived a key')")
edb.execute("INSERT INTO Events VALUES ('4894','Certificate Services imported and archived a key')")
edb.execute("INSERT INTO Events VALUES ('4895','Certificate Services published the CA certificate to Active Directory Domain Services')")
edb.execute("INSERT INTO Events VALUES ('4896','One or more rows have been deleted from the certificate database')")
edb.execute("INSERT INTO Events VALUES ('4897','Role separation enabled')")
edb.execute("INSERT INTO Events VALUES ('4898','Certificate Services loaded a template')")
edb.execute("INSERT INTO Events VALUES ('4899','A Certificate Services template was updated')")
edb.execute("INSERT INTO Events VALUES ('4900','Certificate Services template security was updated')")
edb.execute("INSERT INTO Events VALUES ('4902','The Per-user audit policy table was created')")
edb.execute("INSERT INTO Events VALUES ('4904','An attempt was made to register a security event source')")
edb.execute("INSERT INTO Events VALUES ('4905','An attempt was made to unregister a security event source')")
edb.execute("INSERT INTO Events VALUES ('4906','The CrashOnAuditFail value has changed')")
edb.execute("INSERT INTO Events VALUES ('4907','Auditing settings on object were changed')")
edb.execute("INSERT INTO Events VALUES ('4908','Special Groups Logon table modified')")
edb.execute("INSERT INTO Events VALUES ('4909','The local policy settings for the TBS were changed')")
edb.execute("INSERT INTO Events VALUES ('4910','The group policy settings for the TBS were changed')")
edb.execute("INSERT INTO Events VALUES ('4912','Per User Audit Policy was changed')")
edb.execute("INSERT INTO Events VALUES ('4928','An Active Directory replica source naming context was established')")
edb.execute("INSERT INTO Events VALUES ('4929','An Active Directory replica source naming context was removed')")
edb.execute("INSERT INTO Events VALUES ('4930','An Active Directory replica source naming context was modified')")
edb.execute("INSERT INTO Events VALUES ('4931','An Active Directory replica destination naming context was modified')")
edb.execute("INSERT INTO Events VALUES ('4932','Synchronization of a replica of an Active Directory naming context has begun')")
edb.execute("INSERT INTO Events VALUES ('4933','Synchronization of a replica of an Active Directory naming context has ended')")
edb.execute("INSERT INTO Events VALUES ('4934','Attributes of an Active Directory object were replicated')")
edb.execute("INSERT INTO Events VALUES ('4935','Replication failure begins')")
edb.execute("INSERT INTO Events VALUES ('4936','Replication failure ends')")
edb.execute("INSERT INTO Events VALUES ('4937','A lingering object was removed from a replica')")
edb.execute("INSERT INTO Events VALUES ('4944','The following policy was active when the Windows Firewall started')")
edb.execute("INSERT INTO Events VALUES ('4945','A rule was listed when the Windows Firewall started')")
edb.execute("INSERT INTO Events VALUES ('4946','A change has been made to Windows Firewall exception list. A rule was added')")
edb.execute("INSERT INTO Events VALUES ('4947','A change has been made to Windows Firewall exception list. A rule was modified')")
edb.execute("INSERT INTO Events VALUES ('4948','A change has been made to Windows Firewall exception list. A rule was deleted')")
edb.execute("INSERT INTO Events VALUES ('4949','Windows Firewall settings were restored to the default values')")
edb.execute("INSERT INTO Events VALUES ('4950','A Windows Firewall setting has changed')")
edb.execute("INSERT INTO Events VALUES ('4951','A rule has been ignored because its major version number was not recognized by Windows Firewall')")
edb.execute("INSERT INTO Events VALUES ('4952','Parts of a rule have been ignored because its minor version number was not recognized by Windows Firewall')")
edb.execute("INSERT INTO Events VALUES ('4953','A rule has been ignored by Windows Firewall because it could not parse the rule')")
edb.execute("INSERT INTO Events VALUES ('4954','Windows Firewall Group Policy settings has changed. The new settings have been applied')")
edb.execute("INSERT INTO Events VALUES ('4956','Windows Firewall has changed the active profile')")
edb.execute("INSERT INTO Events VALUES ('4957','Windows Firewall did not apply the following rule')")
edb.execute("INSERT INTO Events VALUES ('4958','Windows Firewall did not apply the following rule because the rule referred to items not configured on this computer')")
edb.execute("INSERT INTO Events VALUES ('4960','IPsec dropped an inbound packet that failed an integrity check')")
edb.execute("INSERT INTO Events VALUES ('4961','IPsec dropped an inbound packet that failed a replay check')")
edb.execute("INSERT INTO Events VALUES ('4962','IPsec dropped an inbound packet that failed a replay check')")
edb.execute("INSERT INTO Events VALUES ('4963','IPsec dropped an inbound clear text packet that should have been secured')")
edb.execute("INSERT INTO Events VALUES ('4964','Special groups have been assigned to a new logon')")
edb.execute("INSERT INTO Events VALUES ('4965','IPsec received a packet from a remote computer with an incorrect Security Parameter Index (SPI).')")
edb.execute("INSERT INTO Events VALUES ('4976','During Main Mode negotiation, IPsec received an invalid negotiation packet.')")
edb.execute("INSERT INTO Events VALUES ('4977','During Quick Mode negotiation, IPsec received an invalid negotiation packet.')")
edb.execute("INSERT INTO Events VALUES ('4978','During Extended Mode negotiation, IPsec received an invalid negotiation packet.')")
edb.execute("INSERT INTO Events VALUES ('4979','IPsec Main Mode and Extended Mode security associations were established.')")
edb.execute("INSERT INTO Events VALUES ('4980','IPsec Main Mode and Extended Mode security associations were established')")
edb.execute("INSERT INTO Events VALUES ('4981','IPsec Main Mode and Extended Mode security associations were established')")
edb.execute("INSERT INTO Events VALUES ('4982','IPsec Main Mode and Extended Mode security associations were established')")
edb.execute("INSERT INTO Events VALUES ('4983','An IPsec Extended Mode negotiation failed')")
edb.execute("INSERT INTO Events VALUES ('4984','An IPsec Extended Mode negotiation failed')")
edb.execute("INSERT INTO Events VALUES ('4985','The state of a transaction has changed')")
edb.execute("INSERT INTO Events VALUES ('5024','The Windows Firewall Service has started successfully')")
edb.execute("INSERT INTO Events VALUES ('5025','The Windows Firewall Service has been stopped')")
edb.execute("INSERT INTO Events VALUES ('5027','The Windows Firewall Service was unable to retrieve the security policy from the local storage')")
edb.execute("INSERT INTO Events VALUES ('5028','The Windows Firewall Service was unable to parse the new security policy.')")
edb.execute("INSERT INTO Events VALUES ('5029','The Windows Firewall Service failed to initialize the driver')")
edb.execute("INSERT INTO Events VALUES ('5030','The Windows Firewall Service failed to start')")
edb.execute("INSERT INTO Events VALUES ('5031','The Windows Firewall Service blocked an application from accepting incoming connections on the network.')")
edb.execute("INSERT INTO Events VALUES ('5032','Windows Firewall was unable to notify the user that it blocked an application from accepting incoming connections on the network')")
edb.execute("INSERT INTO Events VALUES ('5033','The Windows Firewall Driver has started successfully')")
edb.execute("INSERT INTO Events VALUES ('5034','The Windows Firewall Driver has been stopped')")
edb.execute("INSERT INTO Events VALUES ('5035','The Windows Firewall Driver failed to start')")
edb.execute("INSERT INTO Events VALUES ('5037','The Windows Firewall Driver detected critical runtime error. Terminating')")
edb.execute("INSERT INTO Events VALUES ('5038','Code integrity determined that the image hash of a file is not valid')")
edb.execute("INSERT INTO Events VALUES ('5039','A registry key was virtualized.')")
edb.execute("INSERT INTO Events VALUES ('5040','A change has been made to IPsec settings. An Authentication Set was added.')")
edb.execute("INSERT INTO Events VALUES ('5041','A change has been made to IPsec settings. An Authentication Set was modified')")
edb.execute("INSERT INTO Events VALUES ('5042','A change has been made to IPsec settings. An Authentication Set was deleted')")
edb.execute("INSERT INTO Events VALUES ('5043','A change has been made to IPsec settings. A Connection Security Rule was added')")
edb.execute("INSERT INTO Events VALUES ('5044','A change has been made to IPsec settings. A Connection Security Rule was modified')")
edb.execute("INSERT INTO Events VALUES ('5045','A change has been made to IPsec settings. A Connection Security Rule was deleted')")
edb.execute("INSERT INTO Events VALUES ('5046','A change has been made to IPsec settings. A Crypto Set was added')")
edb.execute("INSERT INTO Events VALUES ('5047','A change has been made to IPsec settings. A Crypto Set was modified')")
edb.execute("INSERT INTO Events VALUES ('5048','A change has been made to IPsec settings. A Crypto Set was deleted')")
edb.execute("INSERT INTO Events VALUES ('5049','An IPsec Security Association was deleted')")
edb.execute("INSERT INTO Events VALUES ('5050','An attempt to programmatically disable the Windows Firewall using a call to INetFwProfile.FirewallEnabled(FALSE')")
edb.execute("INSERT INTO Events VALUES ('5051','A file was virtualized')")
edb.execute("INSERT INTO Events VALUES ('5056','A cryptographic self test was performed')")
edb.execute("INSERT INTO Events VALUES ('5057','A cryptographic primitive operation failed')")
edb.execute("INSERT INTO Events VALUES ('5058','Key file operation')")
edb.execute("INSERT INTO Events VALUES ('5059','Key migration operation')")
edb.execute("INSERT INTO Events VALUES ('5060','Verification operation failed')")
edb.execute("INSERT INTO Events VALUES ('5061','Cryptographic operation')")
edb.execute("INSERT INTO Events VALUES ('5062','A kernel-mode cryptographic self test was performed')")
edb.execute("INSERT INTO Events VALUES ('5063','A cryptographic provider operation was attempted')")
edb.execute("INSERT INTO Events VALUES ('5064','A cryptographic context operation was attempted')")
edb.execute("INSERT INTO Events VALUES ('5065','A cryptographic context modification was attempted')")
edb.execute("INSERT INTO Events VALUES ('5066','A cryptographic function operation was attempted')")
edb.execute("INSERT INTO Events VALUES ('5067','A cryptographic function modification was attempted')")
edb.execute("INSERT INTO Events VALUES ('5068','A cryptographic function provider operation was attempted')")
edb.execute("INSERT INTO Events VALUES ('5069','A cryptographic function property operation was attempted')")
edb.execute("INSERT INTO Events VALUES ('5070','A cryptographic function property operation was attempted')")
edb.execute("INSERT INTO Events VALUES ('5120','OCSP Responder Service Started')")
edb.execute("INSERT INTO Events VALUES ('5121','OCSP Responder Service Stopped')")
edb.execute("INSERT INTO Events VALUES ('5122','A Configuration entry changed in the OCSP Responder Service')")
edb.execute("INSERT INTO Events VALUES ('5123','A configuration entry changed in the OCSP Responder Service')")
edb.execute("INSERT INTO Events VALUES ('5124','A security setting was updated on OCSP Responder Service')")
edb.execute("INSERT INTO Events VALUES ('5125','A request was submitted to OCSP Responder Service')")
edb.execute("INSERT INTO Events VALUES ('5126','Signing Certificate was automatically updated by the OCSP Responder Service')")
edb.execute("INSERT INTO Events VALUES ('5127','The OCSP Revocation Provider successfully updated the revocation information')")
edb.execute("INSERT INTO Events VALUES ('5136','A directory service object was modified')")
edb.execute("INSERT INTO Events VALUES ('5137','A directory service object was created')")
edb.execute("INSERT INTO Events VALUES ('5138','A directory service object was undeleted')")
edb.execute("INSERT INTO Events VALUES ('5139','A directory service object was moved')")
edb.execute("INSERT INTO Events VALUES ('5140','A network share object was accessed')")
edb.execute("INSERT INTO Events VALUES ('5141','A directory service object was deleted')")
edb.execute("INSERT INTO Events VALUES ('5142','A network share object was added.')")
edb.execute("INSERT INTO Events VALUES ('5143','A network share object was modified')")
edb.execute("INSERT INTO Events VALUES ('5144','A network share object was deleted.')")
edb.execute("INSERT INTO Events VALUES ('5145','A network share object was checked to see whether client can be granted desired access')")
edb.execute("INSERT INTO Events VALUES ('5148','The Windows Filtering Platform has detected a DoS attack and entered a defensive mode; packets associated with this attack will be discarded.')")
edb.execute("INSERT INTO Events VALUES ('5149','The DoS attack has subsided and normal processing is being resumed.')")
edb.execute("INSERT INTO Events VALUES ('5150','The Windows Filtering Platform has blocked a packet.')")
edb.execute("INSERT INTO Events VALUES ('5151','A more restrictive Windows Filtering Platform filter has blocked a packet.')")
edb.execute("INSERT INTO Events VALUES ('5152','The Windows Filtering Platform blocked a packet')")
edb.execute("INSERT INTO Events VALUES ('5153','A more restrictive Windows Filtering Platform filter has blocked a packet')")
edb.execute("INSERT INTO Events VALUES ('5154','The Windows Filtering Platform has permitted an application or service to listen on a port for incoming connections')")
edb.execute("INSERT INTO Events VALUES ('5155','The Windows Filtering Platform has blocked an application or service from listening on a port for incoming connections')")
edb.execute("INSERT INTO Events VALUES ('5156','The Windows Filtering Platform has allowed a connection')")
edb.execute("INSERT INTO Events VALUES ('5157','The Windows Filtering Platform has blocked a connection')")
edb.execute("INSERT INTO Events VALUES ('5158','The Windows Filtering Platform has permitted a bind to a local port')")
edb.execute("INSERT INTO Events VALUES ('5159','The Windows Filtering Platform has blocked a bind to a local port')")
edb.execute("INSERT INTO Events VALUES ('5168','Spn check for SMB/SMB2 fails.')")
edb.execute("INSERT INTO Events VALUES ('5376','Credential Manager credentials were backed up')")
edb.execute("INSERT INTO Events VALUES ('5377','Credential Manager credentials were restored from a backup')")
edb.execute("INSERT INTO Events VALUES ('5378','The requested credentials delegation was disallowed by policy')")
edb.execute("INSERT INTO Events VALUES ('5440','The following callout was present when the Windows Filtering Platform Base Filtering Engine started')")
edb.execute("INSERT INTO Events VALUES ('5441','The following filter was present when the Windows Filtering Platform Base Filtering Engine started')")
edb.execute("INSERT INTO Events VALUES ('5442','The following provider was present when the Windows Filtering Platform Base Filtering Engine started')")
edb.execute("INSERT INTO Events VALUES ('5443','The following provider context was present when the Windows Filtering Platform Base Filtering Engine started')")
edb.execute("INSERT INTO Events VALUES ('5444','The following sub-layer was present when the Windows Filtering Platform Base Filtering Engine started')")
edb.execute("INSERT INTO Events VALUES ('5446','A Windows Filtering Platform callout has been changed')")
edb.execute("INSERT INTO Events VALUES ('5447','A Windows Filtering Platform filter has been changed')")
edb.execute("INSERT INTO Events VALUES ('5448','A Windows Filtering Platform provider has been changed')")
edb.execute("INSERT INTO Events VALUES ('5449','A Windows Filtering Platform provider context has been changed')")
edb.execute("INSERT INTO Events VALUES ('5450','A Windows Filtering Platform sub-layer has been changed')")
edb.execute("INSERT INTO Events VALUES ('5451','An IPsec Quick Mode security association was established')")
edb.execute("INSERT INTO Events VALUES ('5452','An IPsec Quick Mode security association ended')")
edb.execute("INSERT INTO Events VALUES ('5453','An IPsec negotiation with a remote computer failed because the IKE and AuthIP IPsec Keying Modules (IKEEXT) service is not started')")
edb.execute("INSERT INTO Events VALUES ('5456','PAStore Engine applied Active Directory storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5457','PAStore Engine failed to apply Active Directory storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5458','PAStore Engine applied locally cached copy of Active Directory storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5459','PAStore Engine failed to apply locally cached copy of Active Directory storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5460','PAStore Engine applied local registry storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5461','PAStore Engine failed to apply local registry storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5462','PAStore Engine failed to apply some rules of the active IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5463','PAStore Engine polled for changes to the active IPsec policy and detected no changes')")
edb.execute("INSERT INTO Events VALUES ('5464','PAStore Engine polled for changes to the active IPsec policy, detected changes, and applied them to IPsec Services')")
edb.execute("INSERT INTO Events VALUES ('5465','PAStore Engine received a control for forced reloading of IPsec policy and processed the control successfully')")
edb.execute("INSERT INTO Events VALUES ('5466','PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory cannot be reached, and will use the cached copy of the Active Directory IPsec policy instead')")
edb.execute("INSERT INTO Events VALUES ('5467','PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, and found no changes to the policy')")
edb.execute("INSERT INTO Events VALUES ('5468','PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, found changes to the policy, and applied those changes')")
edb.execute("INSERT INTO Events VALUES ('5471','PAStore Engine loaded local storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5472','PAStore Engine failed to load local storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5473','PAStore Engine loaded directory storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5474','PAStore Engine failed to load directory storage IPsec policy on the computer')")
edb.execute("INSERT INTO Events VALUES ('5477','PAStore Engine failed to add quick mode filter')")
edb.execute("INSERT INTO Events VALUES ('5478','IPsec Services has started successfully')")
edb.execute("INSERT INTO Events VALUES ('5479','IPsec Services has been shut down successfully')")
edb.execute("INSERT INTO Events VALUES ('5480','IPsec Services failed to get the complete list of network interfaces on the computer')")
edb.execute("INSERT INTO Events VALUES ('5483','IPsec Services failed to initialize RPC server. IPsec Services could not be started')")
edb.execute("INSERT INTO Events VALUES ('5484','IPsec Services has experienced a critical failure and has been shut down')")
edb.execute("INSERT INTO Events VALUES ('5485','IPsec Services failed to process some IPsec filters on a plug-and-play event for network interfaces')")
edb.execute("INSERT INTO Events VALUES ('5632','A request was made to authenticate to a wireless network')")
edb.execute("INSERT INTO Events VALUES ('5633','A request was made to authenticate to a wired network')")
edb.execute("INSERT INTO Events VALUES ('5712','A Remote Procedure Call (RPC) was attempted')")
edb.execute("INSERT INTO Events VALUES ('5888','An object in the COM+ Catalog was modified')")
edb.execute("INSERT INTO Events VALUES ('5889','An object was deleted from the COM+ Catalog')")
edb.execute("INSERT INTO Events VALUES ('5890','An object was added to the COM+ Catalog')")
edb.execute("INSERT INTO Events VALUES ('6144','Security policy in the group policy objects has been applied successfully')")
edb.execute("INSERT INTO Events VALUES ('6145','One or more errors occured while processing security policy in the group policy objects')")
edb.execute("INSERT INTO Events VALUES ('6272','Network Policy Server granted access to a user')")
edb.execute("INSERT INTO Events VALUES ('6273','Network Policy Server denied access to a user')")
edb.execute("INSERT INTO Events VALUES ('6274','Network Policy Server discarded the request for a user')")
edb.execute("INSERT INTO Events VALUES ('6275','Network Policy Server discarded the accounting request for a user')")
edb.execute("INSERT INTO Events VALUES ('6276','Network Policy Server quarantined a user')")
edb.execute("INSERT INTO Events VALUES ('6277','Network Policy Server granted access to a user but put it on probation because the host did not meet the defined health policy')")
edb.execute("INSERT INTO Events VALUES ('6278','Network Policy Server granted full access to a user because the host met the defined health policy')")
edb.execute("INSERT INTO Events VALUES ('6279','Network Policy Server locked the user account due to repeated failed authentication attempts')")
edb.execute("INSERT INTO Events VALUES ('6280','Network Policy Server unlocked the user account')")
edb.execute("INSERT INTO Events VALUES ('6281','Code Integrity determined that the page hashes of an image file are not valid...')")
edb.execute("INSERT INTO Events VALUES ('6400','BranchCache: Received an incorrectly formatted response while discovering availability of content.')")
edb.execute("INSERT INTO Events VALUES ('6401','BranchCache: Received invalid data from a peer. Data discarded.')")
edb.execute("INSERT INTO Events VALUES ('6402','BranchCache: The message to the hosted cache offering it data is incorrectly formatted.')")
edb.execute("INSERT INTO Events VALUES ('6403','BranchCache: The hosted cache sent an incorrectly formatted response to the client message to offer it data.')")
edb.execute("INSERT INTO Events VALUES ('6404','BranchCache: Hosted cache could not be authenticated using the provisioned SSL certificate.')")
edb.execute("INSERT INTO Events VALUES ('6405','BranchCache: %2 instance(s) of event id %1 occurred.')")
edb.execute("INSERT INTO Events VALUES ('6406','%1 registered to Windows Firewall to control filtering for the following:')")
edb.execute("INSERT INTO Events VALUES ('6407','%1')")
edb.execute("INSERT INTO Events VALUES ('6408','Registered product %1 failed and Windows Firewall is now controlling the filtering for %2.')")
edb.commit()

file1 = sys.argv[1]
try:
	lol = list(csv.reader(open(file1, 'r', errors="ignore"), delimiter=','))
except:
	print("Error reading file. Please ensure that the file exists and is in propper log2timeline format.")
	sys.exit(1)

header = ['date', 'timezone', 'MACB', 'source', 'sourcetype', 'type', 'user', 'host', 'short', 'desc', 'version', 'filename', 'inode', 'notes', 'format', 'extra']
header2 = ['date', 'timezone', 'MACB', 'source', 'sourcetype', 'type', 'user', 'host', 'short', 'desc', 'version', 'filename', 'inode', 'notes', 'format', 'extra']

tname, textension = os.path.splitext(sys.argv[1])
nfname = tname + ".time"
fo = open(nfname, 'w')

# Create Header
# print("#TIMEFLOW	format version	1")
# print("#TIMEFLOW	source	[source unspecified]")
# print("#TIMEFLOW	description	")
# for item in header:
# 	if item =="date":
# 		print("#TIMEFLOW\tfield\t" + item + "\tDate/Time")
# 	else:
# 		if item =="time":
# 			continue
# 		else:
# 			print("#TIMEFLOW\tfield\t" + item + "\tText")
# print("#TIMEFLOW	end-metadata")
# print("#TIMEFLOW	alias	TIMEFLOW_START	date")
# print("#TIMEFLOW	alias	TIMEFLOW_LABEL	short")
# print("#TIMEFLOW	alias	TIMEFLOW_TRACK	desc")
# print("#TIMEFLOW	====== End of Header. Data below is in tab-delimited format. =====")
# print('\t'.join(header))

fo.write("#TIMEFLOW	format version	1\n")
fo.write("#TIMEFLOW	source	[source unspecified]\n")
fo.write("#TIMEFLOW	description	\n")
for item in header:
	if item =="date":
		fo.write("#TIMEFLOW\tfield\t" + item + "\tDate/Time\n")
	else:
		if item =="time":
			continue
		else:
			fo.write("#TIMEFLOW\tfield\t" + item + "\tText\n")
fo.write("#TIMEFLOW	end-metadata\n")
fo.write("#TIMEFLOW	alias	TIMEFLOW_START	date\n")
fo.write("#TIMEFLOW	alias	TIMEFLOW_LABEL	short\n")
fo.write("#TIMEFLOW	alias	TIMEFLOW_TRACK	desc\n")
fo.write("#TIMEFLOW	====== End of Header. Data below is in tab-delimited format. =====\n")
fo.write('\t'.join(header)+"\n")

numlines = len(lol)
curline = 0

print("Starting conversion now.")
print("Number of lines:", numlines)

for item in lol:
	sobj = item[0].split(":")
	if len(sobj) == 2:
		item[0] = sobj[1]

	if item[0] == "date":
		continue
	if item[0][0] == "#":
		continue
	item[0] = item[0] + " " + item[1]
	#item[0] = item[0]+" "+item[1]
	start_date = datetime.strptime(item[0],'%m/%d/%Y %H:%M:%S')
	item[0] = start_date.strftime('%b %d %Y %H:%M:%S')
	del item[1]
	if item[4] == "WinEVT":
		#item[6] = UID
		nobj = item[8].split(";")
		sobj = nobj[0].split("/")
		eid = sobj[1]
		definition = ""
		results = edb.execute("SELECT * FROM Events WHERE eventid ='" + eid + "'")
		tmp = results.fetchone()
		if tmp:
			definition = ':'.join(tmp)
		item[8] = definition + " : " + item[8]
	if item[4] == "WinEVTX":
		#item[6] = UID
		nobj = item[8].split(":")
		eid = nobj[1]
		print(eid)
		definition = ""
		results = edb.execute("SELECT * FROM Events WHERE eventid ='" + eid + "'")
		tmp = results.fetchone()
		if tmp:
			definition = ':'.join(tmp)
		item[8] = definition + " : " + item[8]

	#print('\t'.join(item))
	curline = curline + 1
	progress = int(curline / numlines * 100)
	#sys.stdout.write('\r[{0}] {1}%'.format('#'*(progress/10), progress))
	#sys.stdout.write("Reading Line:    \r%d%%" %curline)
	sys.stdout.write(" Complete\r%d%%" %progress)
	sys.stdout.flush()

	# for eline in item:
	# 	eline = remove_non_ascii(eline)
	#fo.write(remove_non_ascii('\t'.join(item)+"\n"))
	fo.write('\t'.join(item)+"\n")
fo.close()
sys.stdout.write(" Complete\r%d%%" %100)
print("\nFile completed successfully\nOutput filename: ", nfname)